// Mapper copied from Notion's code and adjusted

export const LANGUAGE_MAPPER: Record<string, string> = {
  //   ABAP: 'abap',  NOT SUPPORTED
  //   Agda: 'agda',  NOT SUPPORTED
  Arduino: 'arduino',
  Assembly: 'nasm',
  Bash: 'bash',
  BASIC: 'basic',
  BNF: 'bnf',
  C: 'c',
  'C#': 'csharp',
  'C++': 'cpp',
  Clojure: 'clojure',
  CoffeeScript: 'coffeescript',
  Coq: 'coq',
  CSS: 'css',
  Dart: 'dart',
  //   Dhall: 'dhall', NOT SUPPORTED
  Diff: 'diff',
  Docker: 'docker',
  EBNF: 'ebnf',
  Elixir: 'elixir',
  Elm: 'elm',
  Erlang: 'erlang',
  'F#': 'fsharp',
  //   Flow: 'flow',  NOT SUPPORTED
  Fortran: 'fortran',
  Gherkin: 'gherkin',
  GLSL: 'glsl',
  Go: 'go',
  GraphQL: 'graphql',
  Groovy: 'groovy',
  Haskell: 'haskell',
  HTML: 'html',
  //   Idris: 'idris',  NOT SUPPORTED
  Java: 'java',
  JavaScript: 'jsx',
  JSON: 'json',
  Julia: 'julia',
  Kotlin: 'kotlin',
  LaTeX: 'latex',
  Less: 'less',
  Lisp: 'lisp',
  LiveScript: 'livescript',
  'LLVM IR': 'llvm',
  Lua: 'lua',
  Makefile: 'makefile',
  Markdown: 'markdown',
  Markup: 'markup',
  MATLAB: 'matlab',
  Mathematica: 'mathematica',
  //   Mermaid: 'mermaid',  NOT SUPPORTED
  Nix: 'nix',
  'Objective-C': 'objectivec',
  OCaml: 'ocaml',
  Pascal: 'pascal',
  Perl: 'perl',
  PHP: 'php',
  'Plain Text': 'null',
  PowerShell: 'powershell',
  Prolog: 'prolog',
  Protobuf: 'protobuf',
  //   PureScript: 'purescript',  NOT SUPPORTED
  Python: 'python',
  R: 'r',
  //   Racket: 'racket', NOT SUPPORTED
  Reason: 'reason',
  Ruby: 'ruby',
  Rust: 'rust',
  Sass: 'sass',
  Scala: 'scala',
  Scheme: 'scheme',
  Scss: 'scss',
  Shell: 'bash',
  Solidity: 'solidity',
  SQL: 'sql',
  Swift: 'swift',
  TOML: 'toml',
  TypeScript: 'tsx',
  'VB.Net': 'vbnet',
  Verilog: 'verilog',
  VHDL: 'vhdl',
  'Visual Basic': 'visual-basic',
  WebAssembly: 'wasm',
  XML: 'xml',
  YAML: 'yaml'
};
