export const themes = {
  '3024': { originalName: 'base16/3024', type: 'dark' },
  'A11y Dark': { originalName: 'a11y-dark', type: 'dark' },
  'A11y Light': { originalName: 'a11y-light', type: 'light' },
  Agate: { originalName: 'agate', type: 'dark' },
  'An Old Hope': { originalName: 'an-old-hope', type: 'dark' },
  Androidstudio: { originalName: 'androidstudio', type: 'dark' },
  Apathy: { originalName: 'base16/apathy', type: 'dark' },
  Apprentice: { originalName: 'base16/apprentice', type: 'dark' },
  'Arduino Light': { originalName: 'arduino-light', type: 'light' },
  Arta: { originalName: 'arta', type: 'dark' },
  Ascetic: { originalName: 'ascetic', type: 'dark' },
  Ashes: { originalName: 'base16/ashes', type: 'dark' },
  'Atelier Cave': { originalName: 'base16/atelier-cave', type: 'dark' },
  'Atelier Cave Light': { originalName: 'base16/atelier-cave-light', type: 'light' },
  'Atelier Dune': { originalName: 'base16/atelier-dune', type: 'dark' },
  'Atelier Dune Light': { originalName: 'base16/atelier-dune-light', type: 'light' },
  'Atelier Estuary': { originalName: 'base16/atelier-estuary', type: 'dark' },
  'Atelier Estuary Light': { originalName: 'base16/atelier-estuary-light', type: 'light' },
  'Atelier Forest': { originalName: 'base16/atelier-forest', type: 'dark' },
  'Atelier Forest Light': { originalName: 'base16/atelier-forest-light', type: 'light' },
  'Atelier Heath': { originalName: 'base16/atelier-heath', type: 'dark' },
  'Atelier Heath Light': { originalName: 'base16/atelier-heath-light', type: 'light' },
  'Atelier Lakeside': { originalName: 'base16/atelier-lakeside', type: 'dark' },
  'Atelier Lakeside Light': { originalName: 'base16/atelier-lakeside-light', type: 'light' },
  'Atelier Plateau': { originalName: 'base16/atelier-plateau', type: 'dark' },
  'Atelier Plateau Light': { originalName: 'base16/atelier-plateau-light', type: 'light' },
  'Atelier Savanna': { originalName: 'base16/atelier-savanna', type: 'dark' },
  'Atelier Savanna Light': { originalName: 'base16/atelier-savanna-light', type: 'light' },
  'Atelier Seaside': { originalName: 'base16/atelier-seaside', type: 'dark' },
  'Atelier Seaside Light': { originalName: 'base16/atelier-seaside-light', type: 'light' },
  'Atelier Sulphurpool': { originalName: 'base16/atelier-sulphurpool', type: 'dark' },
  'Atelier Sulphurpool Light': { originalName: 'base16/atelier-sulphurpool-light', type: 'light' },
  Atlas: { originalName: 'base16/atlas', type: 'dark' },
  'Atom One Dark': { originalName: 'atom-one-dark', type: 'dark' },
  'Atom One Dark Reasonable': { originalName: 'atom-one-dark-reasonable', type: 'dark' },
  'Atom One Light': { originalName: 'atom-one-light', type: 'light' },
  Bespin: { originalName: 'base16/bespin', type: 'dark' },
  'Black Metal': { originalName: 'base16/black-metal', type: 'dark' },
  'Black Metal Bathory': { originalName: 'base16/black-metal-bathory', type: 'dark' },
  'Black Metal Burzum': { originalName: 'base16/black-metal-burzum', type: 'dark' },
  'Black Metal Dark-funeral': { originalName: 'base16/black-metal-dark-funeral', type: 'dark' },
  'Black Metal Gorgoroth': { originalName: 'base16/black-metal-gorgoroth', type: 'dark' },
  'Black Metal Immortal': { originalName: 'base16/black-metal-immortal', type: 'dark' },
  'Black Metal Khold': { originalName: 'base16/black-metal-khold', type: 'dark' },
  'Black Metal Marduk': { originalName: 'base16/black-metal-marduk', type: 'dark' },
  'Black Metal Mayhem': { originalName: 'base16/black-metal-mayhem', type: 'dark' },
  'Black Metal Nile': { originalName: 'base16/black-metal-nile', type: 'dark' },
  'Black Metal Venom': { originalName: 'base16/black-metal-venom', type: 'dark' },
  Brewer: { originalName: 'base16/brewer', type: 'dark' },
  Bright: { originalName: 'base16/bright', type: 'dark' },
  Brogrammer: { originalName: 'base16/brogrammer', type: 'dark' },
  'Brown Paper': { originalName: 'brown-paper', type: 'light' },
  'Brown Papersq': { originalName: 'brown-papersq', type: 'dark' },
  'Brush Trees': { originalName: 'base16/brush-trees', type: 'light' },
  'Brush Trees-dark': { originalName: 'base16/brush-trees-dark', type: 'dark' },
  Chalk: { originalName: 'base16/chalk', type: 'dark' },
  Circus: { originalName: 'base16/circus', type: 'dark' },
  'Classic Dark': { originalName: 'base16/classic-dark', type: 'dark' },
  'Classic Light': { originalName: 'base16/classic-light', type: 'light' },
  'Codepen Embed': { originalName: 'codepen-embed', type: 'dark' },
  Codeschool: { originalName: 'base16/codeschool', type: 'dark' },
  'Color Brewer': { originalName: 'color-brewer', type: 'light' },
  Colors: { originalName: 'base16/colors', type: 'dark' },
  Cupcake: { originalName: 'base16/cupcake', type: 'light' },
  Cupertino: { originalName: 'base16/cupertino', type: 'light' },
  Danqing: { originalName: 'base16/danqing', type: 'dark' },
  Darcula: { originalName: 'base16/darcula', type: 'dark' },
  Dark: { originalName: 'dark', type: 'dark' },
  'Dark Violet': { originalName: 'base16/dark-violet', type: 'dark' },
  Darkmoss: { originalName: 'base16/darkmoss', type: 'dark' },
  Darktooth: { originalName: 'base16/darktooth', type: 'dark' },
  Decaf: { originalName: 'base16/decaf', type: 'dark' },
  Default: { originalName: 'default', type: 'dark' },
  'Default Dark': { originalName: 'base16/default-dark', type: 'dark' },
  'Default Light': { originalName: 'base16/default-light', type: 'light' },
  Devibeans: { originalName: 'devibeans', type: 'dark' },
  Dirtysea: { originalName: 'base16/dirtysea', type: 'dark' },
  Docco: { originalName: 'docco', type: 'light' },
  Dracula: { originalName: 'base16/dracula', type: 'dark' },
  'Edge Dark': { originalName: 'base16/edge-dark', type: 'dark' },
  'Edge Light': { originalName: 'base16/edge-light', type: 'light' },
  Eighties: { originalName: 'base16/eighties', type: 'dark' },
  Embers: { originalName: 'base16/embers', type: 'dark' },
  'Equilibrium Dark': { originalName: 'base16/equilibrium-dark', type: 'dark' },
  'Equilibrium Gray Dark': { originalName: 'base16/equilibrium-gray-dark', type: 'dark' },
  'Equilibrium Gray Light': { originalName: 'base16/equilibrium-gray-light', type: 'light' },
  'Equilibrium Light': { originalName: 'base16/equilibrium-light', type: 'light' },
  Espresso: { originalName: 'base16/espresso', type: 'dark' },
  Eva: { originalName: 'base16/eva', type: 'dark' },
  'Eva Dim': { originalName: 'base16/eva-dim', type: 'dark' },
  Far: { originalName: 'far', type: 'dark' },
  Felipec: { originalName: 'felipec', type: 'dark' },
  Flat: { originalName: 'base16/flat', type: 'dark' },
  Foundation: { originalName: 'foundation', type: 'light' },
  Framer: { originalName: 'base16/framer', type: 'dark' },
  'Fruit Soda': { originalName: 'base16/fruit-soda', type: 'light' },
  Gigavolt: { originalName: 'base16/gigavolt', type: 'dark' },
  Github: { originalName: 'github', type: 'light' },
  'Github Dark': { originalName: 'github-dark', type: 'dark' },
  'Github Dark Dimmed': { originalName: 'github-dark-dimmed', type: 'dark' },
  Gml: { originalName: 'gml', type: 'dark' },
  'Google Dark': { originalName: 'base16/google-dark', type: 'dark' },
  'Google Light': { originalName: 'base16/google-light', type: 'light' },
  Googlecode: { originalName: 'googlecode', type: 'light' },
  'Gradient Dark': { originalName: 'gradient-dark', type: 'dark' },
  'Gradient Light': { originalName: 'gradient-light', type: 'light' },
  Grayscale: { originalName: 'grayscale', type: 'light' },
  'Grayscale Dark': { originalName: 'base16/grayscale-dark', type: 'dark' },
  'Grayscale Light': { originalName: 'base16/grayscale-light', type: 'light' },
  'Green Screen': { originalName: 'base16/green-screen', type: 'dark' },
  'Gruvbox Dark Hard': { originalName: 'base16/gruvbox-dark-hard', type: 'dark' },
  'Gruvbox Dark Medium': { originalName: 'base16/gruvbox-dark-medium', type: 'dark' },
  'Gruvbox Dark Pale': { originalName: 'base16/gruvbox-dark-pale', type: 'dark' },
  'Gruvbox Dark Soft': { originalName: 'base16/gruvbox-dark-soft', type: 'dark' },
  'Gruvbox Light Hard': { originalName: 'base16/gruvbox-light-hard', type: 'light' },
  'Gruvbox Light Medium': { originalName: 'base16/gruvbox-light-medium', type: 'light' },
  'Gruvbox Light Soft': { originalName: 'base16/gruvbox-light-soft', type: 'light' },
  Hardcore: { originalName: 'base16/hardcore', type: 'dark' },
  'Harmonic16 Dark': { originalName: 'base16/harmonic16-dark', type: 'dark' },
  'Harmonic16 Light': { originalName: 'base16/harmonic16-light', type: 'light' },
  'Heetch Dark': { originalName: 'base16/heetch-dark', type: 'dark' },
  'Heetch Light': { originalName: 'base16/heetch-light', type: 'light' },
  Helios: { originalName: 'base16/helios', type: 'dark' },
  Hopscotch: { originalName: 'base16/hopscotch', type: 'dark' },
  'Horizon Dark': { originalName: 'base16/horizon-dark', type: 'dark' },
  'Horizon Light': { originalName: 'base16/horizon-light', type: 'light' },
  'Humanoid Dark': { originalName: 'base16/humanoid-dark', type: 'dark' },
  'Humanoid Light': { originalName: 'base16/humanoid-light', type: 'light' },
  Hybrid: { originalName: 'hybrid', type: 'dark' },
  'Ia Dark': { originalName: 'base16/ia-dark', type: 'dark' },
  'Ia Light': { originalName: 'base16/ia-light', type: 'light' },
  'Icy Dark': { originalName: 'base16/icy-dark', type: 'dark' },
  Idea: { originalName: 'idea', type: 'light' },
  'Intellij Light': { originalName: 'intellij-light', type: 'light' },
  'Ir Black': { originalName: 'ir-black', type: 'dark' },
  'Isbl Editor Dark': { originalName: 'isbl-editor-dark', type: 'dark' },
  'Isbl Editor Light': { originalName: 'isbl-editor-light', type: 'light' },
  Isotope: { originalName: 'base16/isotope', type: 'dark' },
  Kimber: { originalName: 'base16/kimber', type: 'dark' },
  'Kimbie Dark': { originalName: 'kimbie-dark', type: 'dark' },
  'Kimbie Light': { originalName: 'kimbie-light', type: 'light' },
  Lightfair: { originalName: 'lightfair', type: 'light' },
  Lioshi: { originalName: 'lioshi', type: 'dark' },
  'London Tube': { originalName: 'base16/london-tube', type: 'dark' },
  Macintosh: { originalName: 'base16/macintosh', type: 'dark' },
  Magula: { originalName: 'magula', type: 'light' },
  Marrakesh: { originalName: 'base16/marrakesh', type: 'dark' },
  Materia: { originalName: 'base16/materia', type: 'dark' },
  Material: { originalName: 'base16/material', type: 'dark' },
  'Material Darker': { originalName: 'base16/material-darker', type: 'dark' },
  'Material Lighter': { originalName: 'base16/material-lighter', type: 'light' },
  'Material Palenight': { originalName: 'base16/material-palenight', type: 'dark' },
  'Material Vivid': { originalName: 'base16/material-vivid', type: 'dark' },
  'Mellow Purple': { originalName: 'base16/mellow-purple', type: 'dark' },
  'Mexico Light': { originalName: 'base16/mexico-light', type: 'light' },
  Mocha: { originalName: 'base16/mocha', type: 'dark' },
  'Mono Blue': { originalName: 'mono-blue', type: 'light' },
  Monokai: { originalName: 'monokai', type: 'dark' },
  'Monokai Sublime': { originalName: 'monokai-sublime', type: 'dark' },
  Nebula: { originalName: 'base16/nebula', type: 'dark' },
  'Night Owl': { originalName: 'night-owl', type: 'dark' },
  'Nnfx Dark': { originalName: 'nnfx-dark', type: 'dark' },
  'Nnfx Light': { originalName: 'nnfx-light', type: 'light' },
  Nord: { originalName: 'nord', type: 'dark' },
  Nova: { originalName: 'base16/nova', type: 'dark' },
  Obsidian: { originalName: 'obsidian', type: 'dark' },
  Ocean: { originalName: 'base16/ocean', type: 'dark' },
  Oceanicnext: { originalName: 'base16/oceanicnext', type: 'dark' },
  'One Light': { originalName: 'base16/one-light', type: 'light' },
  Onedark: { originalName: 'base16/onedark', type: 'dark' },
  'Outrun Dark': { originalName: 'base16/outrun-dark', type: 'dark' },
  'Panda Syntax Dark': { originalName: 'panda-syntax-dark', type: 'dark' },
  'Panda Syntax Light': { originalName: 'panda-syntax-light', type: 'light' },
  'Papercolor Dark': { originalName: 'base16/papercolor-dark', type: 'dark' },
  'Papercolor Light': { originalName: 'base16/papercolor-light', type: 'light' },
  Paraiso: { originalName: 'base16/paraiso', type: 'dark' },
  'Paraiso Dark': { originalName: 'paraiso-dark', type: 'dark' },
  'Paraiso Light': { originalName: 'paraiso-light', type: 'light' },
  Pasque: { originalName: 'base16/pasque', type: 'dark' },
  Phd: { originalName: 'base16/phd', type: 'dark' },
  Pico: { originalName: 'base16/pico', type: 'dark' },
  Pojoaque: { originalName: 'pojoaque', type: 'dark' },
  Pop: { originalName: 'base16/pop', type: 'dark' },
  Porple: { originalName: 'base16/porple', type: 'dark' },
  Purebasic: { originalName: 'purebasic', type: 'light' },
  'Qtcreator Dark': { originalName: 'qtcreator-dark', type: 'dark' },
  'Qtcreator Light': { originalName: 'qtcreator-light', type: 'light' },
  Qualia: { originalName: 'base16/qualia', type: 'dark' },
  Railscasts: { originalName: 'base16/railscasts', type: 'dark' },
  Rainbow: { originalName: 'rainbow', type: 'dark' },
  Rebecca: { originalName: 'base16/rebecca', type: 'dark' },
  'Ros Pine': { originalName: 'base16/ros-pine', type: 'dark' },
  'Ros Pine Dawn': { originalName: 'base16/ros-pine-dawn', type: 'light' },
  'Ros Pine Moon': { originalName: 'base16/ros-pine-moon', type: 'dark' },
  Routeros: { originalName: 'routeros', type: 'light' },
  Sagelight: { originalName: 'base16/sagelight', type: 'light' },
  Sandcastle: { originalName: 'base16/sandcastle', type: 'dark' },
  'School Book': { originalName: 'school-book', type: 'light' },
  'Seti Ui': { originalName: 'base16/seti-ui', type: 'dark' },
  'Shades Of Purple': { originalName: 'shades-of-purple', type: 'dark' },
  Shapeshifter: { originalName: 'base16/shapeshifter', type: 'light' },
  'Silk Dark': { originalName: 'base16/silk-dark', type: 'dark' },
  'Silk Light': { originalName: 'base16/silk-light', type: 'light' },
  Snazzy: { originalName: 'base16/snazzy', type: 'dark' },
  'Solar Flare': { originalName: 'base16/solar-flare', type: 'dark' },
  'Solar Flare Light': { originalName: 'base16/solar-flare-light', type: 'light' },
  'Solarized Dark': { originalName: 'base16/solarized-dark', type: 'dark' },
  'Solarized Light': { originalName: 'base16/solarized-light', type: 'light' },
  Spacemacs: { originalName: 'base16/spacemacs', type: 'dark' },
  Srcery: { originalName: 'srcery', type: 'dark' },
  'Stackoverflow Dark': { originalName: 'stackoverflow-dark', type: 'dark' },
  'Stackoverflow Light': { originalName: 'stackoverflow-light', type: 'light' },
  Summercamp: { originalName: 'base16/summercamp', type: 'dark' },
  'Summerfruit Dark': { originalName: 'base16/summerfruit-dark', type: 'dark' },
  'Summerfruit Light': { originalName: 'base16/summerfruit-light', type: 'light' },
  Sunburst: { originalName: 'sunburst', type: 'dark' },
  'Synth Midnight Terminal Dark': { originalName: 'base16/synth-midnight-terminal-dark', type: 'dark' },
  'Synth Midnight Terminal Light': { originalName: 'base16/synth-midnight-terminal-light', type: 'light' },
  Tango: { originalName: 'base16/tango', type: 'dark' },
  Tender: { originalName: 'base16/tender', type: 'dark' },
  'Tokyo Night Dark': { originalName: 'tokyo-night-dark', type: 'dark' },
  'Tokyo Night Light': { originalName: 'tokyo-night-light', type: 'light' },
  Tomorrow: { originalName: 'base16/tomorrow', type: 'dark' },
  'Tomorrow Night': { originalName: 'base16/tomorrow-night', type: 'dark' },
  'Tomorrow Night Blue': { originalName: 'tomorrow-night-blue', type: 'dark' },
  'Tomorrow Night Bright': { originalName: 'tomorrow-night-bright', type: 'dark' },
  Twilight: { originalName: 'base16/twilight', type: 'dark' },
  'Unikitty Dark': { originalName: 'base16/unikitty-dark', type: 'dark' },
  'Unikitty Light': { originalName: 'base16/unikitty-light', type: 'light' },
  Vs: { originalName: 'vs', type: 'light' },
  Vs2015: { originalName: 'vs2015', type: 'dark' },
  Vulcan: { originalName: 'base16/vulcan', type: 'dark' },
  'Windows 10': { originalName: 'base16/windows-10', type: 'dark' },
  'Windows 10 Light': { originalName: 'base16/windows-10-light', type: 'light' },
  'Windows 95': { originalName: 'base16/windows-95', type: 'dark' },
  'Windows 95 Light': { originalName: 'base16/windows-95-light', type: 'light' },
  'Windows High Contrast': { originalName: 'base16/windows-high-contrast', type: 'dark' },
  'Windows High Contrast Light': { originalName: 'base16/windows-high-contrast-light', type: 'light' },
  'Windows Nt': { originalName: 'base16/windows-nt', type: 'dark' },
  'Windows Nt Light': { originalName: 'base16/windows-nt-light', type: 'light' },
  Woodland: { originalName: 'base16/woodland', type: 'dark' },
  Xcode: { originalName: 'xcode', type: 'light' },
  'Xcode Dusk': { originalName: 'base16/xcode-dusk', type: 'dark' },
  Xt256: { originalName: 'xt256', type: 'dark' },
  Zenburn: { originalName: 'base16/zenburn', type: 'dark' }
} as const;

export const adjustId = (theme: ThemeName) => {
  return theme.toLowerCase().replaceAll(' ', '-');
};

export type ThemeName = keyof typeof themes;
